# -*- coding: utf-8 -*-
"""Forecasting-Metode-Regresi-Linear-Kelompok-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17v_fsI5_u-YByIEl7MkZCJMaAHa30Fsv
"""

#loading dataset
import pandas as pd
import numpy as np

data = pd.read_excel('dataset_Nvidia.xlsx') #nama dataset disesuaikan
data.head()

#pemilihan fitur dan target

data['Date'] = pd.to_datetime(data['Date'])
data['Date'] = data['Date'].map(pd.Timestamp.toordinal)


X = data[['Date']] #fitur patokan prediksi
y = data['Close'] #fitur yang akan diprediksi

#pembagian dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Ukuran data latih X: {X_train.shape}")
print(f"Ukuran data uji X: {X_test.shape}")
print(f"Ukuran data latih y: {y_train.shape}")
print(f"Ukuran data uji y: {y_test.shape}")

#Training
#model prediksi (contoh: Linear Regression)
from sklearn.linear_model import LinearRegression

# Inisialisasi model
model = LinearRegression()

# Melatih model menggunakan data latih
print("Melatih model...")
model.fit(X_train, y_train)
print("Model berhasil dilatih!")

# Membuat prediksi pada data uji
# Prediksi pada data uji
y_pred = model.predict(X_test)

# Ambil 5 hari pertama
pd.DataFrame({
    "Actual": y_test[:5],
    "Predicted": y_pred[:5]
})

# Jumlah hari ke depan
n_future = 30

# Ambil tanggal terakhir
last_date = data['Date'].iloc[-1]

# Buat tanggal masa depan
future_dates = pd.date_range(
    start=pd.Timestamp.fromordinal(last_date) + pd.Timedelta(days=1),
    periods=n_future
)

# Konversi tanggal masa depan ke ordinal (SESUAI TRAINING)
X_future = pd.DataFrame({
    'Date': future_dates.map(pd.Timestamp.toordinal)
})

# Prediksi
future_pred = model.predict(X_future)

# Gabungkan hasil
forecast_df = pd.DataFrame({
    'Date': future_dates,
    'Predicted Close': future_pred
})

display(forecast_df)

#Pengujian
from sklearn.metrics import mean_squared_error
import numpy as np

# Menghitung Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse:.2f}")

# Menghitung Mean Absolute Percentage Error (MAPE) secara inline
y_true_np, y_pred_np = np.array(y_test), np.array(y_pred)
non_zero_mask = y_true_np != 0

if np.sum(non_zero_mask) == 0:
    mape = np.nan # Atau tangani sesuai kebijakan Anda jika semua y_true adalah nol
else:
    mape = np.mean(np.abs((y_true_np[non_zero_mask] - y_pred_np[non_zero_mask]) / y_true_np[non_zero_mask])) * 100

print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

import matplotlib.pyplot as plt

# Buat salinan tanggal dalam format datetime untuk plotting
data_plot = data.copy()
data_plot['Date_plot'] = pd.to_datetime(
    data_plot['Date'].apply(pd.Timestamp.fromordinal)
)

plt.figure(figsize=(14,6))

# ===============================
# 1. DATA AKTUAL (SEMUA)
# ===============================
plt.plot(
    data_plot['Date_plot'],
    data_plot['Close'],
    label='Harga Aktual'
)

# ===============================
# 2. HASIL PREDIKSI DATA UJI
# ===============================
plt.plot(
    data_plot.loc[X_test.index, 'Date_plot'],
    y_pred,
    label='Prediksi (Data Uji)'
)

# ===============================
# 3. PREDIKSI 1 BULAN KE DEPAN
# ===============================
plt.plot(
    forecast_df['Date'],
    forecast_df['Predicted Close'],
    label='Prediksi 1 Bulan ke Depan',
    linestyle='--'
)

# ===============================
# 4. PENGATURAN GRAFIK
# ===============================
plt.title('Harga Saham: Data Aktual, Prediksi, dan Forecast 1 Bulan')
plt.xlabel('Tanggal')
plt.ylabel('Harga Penutupan')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()



